### ISSUE TITLE
Opacity hedaer

### ISSUE THREAD

**Issue by fpmweb** [krisrak/appframework-templates#1]
Hello, 

first of all congratulate you for the good work :) 

I'm trying to give effect to the header opacity in the style to make it look iOS7 the content scrolling. 

Is possible? I built this how the DOM is not viable. 
What do you think? 

Thank you!

**Comment by krisrak** [comment]
No, the content `div` starts below the `header`, so the content wont show below the `header` if you change the opacity of header

**Comment by fpmweb** [comment]
Ok, thank you. 
believe it.
