### ISSUE TITLE
Login View Template

### ISSUE THREAD

**Issue by notorioushanz** [krisrak/appframework-templates#6]
Hello,

How you get username and login in signup element to use in javascript?
I did getelementbyid("signup") and get an object. But i don't know how to get username and password properties.

**Comment by gabicristina** [comment]
Hi!

You could get it using <code>document.getElementsByName("username")[0].value;</code>
This link might help you: http://stackoverflow.com/a/11563667

**Comment by notorioushanz** [comment]
Thank you! i did not see your answer back then.
